import type { GalleryCategoryOption, GalleryItem } from "@/types/gallery";

export const GALLERY_CONTENT = {
  eyebrow: "Gallery",
  title: "Craftsmanship in Every Detail",
  description:
    "Explore our portfolio of aluminium windows, sliding doors, glass partitions, facades, and interior executions across Vadodara and Gujarat.",
} as const;

export const GALLERY_SEO_KEYWORDS = [
  "aluminium windows vadodara",
  "sliding doors vadodara",
  "glass partitions vadodara",
  "ACP cladding vadodara",
  "aluminium windows gallery",
  "structural glazing portfolio",
  "false ceiling work vadodara",
  "Shree Chamunda Aluminium gallery",
] as const;

export const GALLERY_CATEGORIES: GalleryCategoryOption[] = [
  { value: "all", label: "All" },
  { value: "aluminium-windows", label: "Aluminium Windows" },
  { value: "sliding-doors", label: "Sliding Doors" },
  { value: "glass-partitions", label: "Glass Partitions" },
  { value: "acp-cladding", label: "ACP Cladding" },
  { value: "structural-glazing", label: "Structural Glazing" },
  { value: "false-ceiling", label: "False Ceiling" },
  { value: "interior-work", label: "Interior Work" },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "aw-01",
    title: "Panoramic Living Room Windows",
    category: "aluminium-windows",
    alt: "Floor-to-ceiling aluminium windows in luxury living room",
    src: "/images/gallery/aluminium-windows-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "aw-02",
    title: "Slim Profile Casement Windows",
    category: "aluminium-windows",
    alt: "Slim profile casement aluminium windows on modern facade",
    src: "/images/gallery/aluminium-windows-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "aw-03",
    title: "Corner Window Assembly",
    category: "aluminium-windows",
    alt: "Corner aluminium window assembly with minimal framing",
    src: "/images/gallery/aluminium-windows-03.svg",
    width: 800,
    height: 600,
  },
  {
    id: "sd-01",
    title: "Sliding Terrace Doors",
    category: "sliding-doors",
    alt: "Multi-track sliding doors opening to terrace",
    src: "/images/gallery/sliding-doors-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "sd-02",
    title: "Pool Deck Sliding System",
    category: "sliding-doors",
    alt: "Sliding door system connecting interior to pool deck",
    src: "/images/gallery/sliding-doors-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "gp-01",
    title: "Frameless Office Partitions",
    category: "glass-partitions",
    alt: "Frameless glass partitions in corporate office",
    src: "/images/gallery/glass-partitions-01.svg",
    width: 800,
    height: 600,
  },
  {
    id: "gp-02",
    title: "Glass Meeting Room",
    category: "glass-partitions",
    alt: "Acoustic glass meeting room with aluminium frame",
    src: "/images/gallery/glass-partitions-02.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "acp-01",
    title: "ACP Cladding Elevation",
    category: "acp-cladding",
    alt: "ACP cladding facade with clean panel lines",
    src: "/images/gallery/acp-cladding-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "acp-02",
    title: "Retail Facade Cladding",
    category: "acp-cladding",
    alt: "Aluminium composite panel cladding on retail building",
    src: "/images/gallery/acp-cladding-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "sg-01",
    title: "Curtain Wall Glazing",
    category: "structural-glazing",
    alt: "Commercial curtain wall structural glazing",
    src: "/images/gallery/structural-glazing-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "sg-02",
    title: "Entrance Structural Glazing",
    category: "structural-glazing",
    alt: "Structural glass entrance canopy at commercial building",
    src: "/images/gallery/structural-glazing-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "fc-01",
    title: "Gypsum False Ceiling",
    category: "false-ceiling",
    alt: "Gypsum false ceiling with recessed lighting",
    src: "/images/gallery/false-ceiling-01.svg",
    width: 800,
    height: 600,
  },
  {
    id: "fc-02",
    title: "Office Ceiling Integration",
    category: "false-ceiling",
    alt: "False ceiling integrating HVAC and lighting in office",
    src: "/images/gallery/false-ceiling-02.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "iw-01",
    title: "Azure Office Fit-Out",
    category: "interior-work",
    alt: "Complete office interior with partitions and ceiling",
    src: "/images/gallery/interior-work-01.svg",
    width: 800,
    height: 600,
  },
  {
    id: "iw-02",
    title: "Showroom Interior",
    category: "interior-work",
    alt: "Retail showroom aluminium and glass interior",
    src: "/images/gallery/interior-work-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "iw-03",
    title: "Residential Interior Package",
    category: "interior-work",
    alt: "Residential interior aluminium and glass package",
    src: "/images/gallery/interior-work-03.svg",
    width: 800,
    height: 1000,
  },
];
