import type { GalleryCategoryOption, GalleryItem } from "@/types/gallery";

export const GALLERY_CONTENT = {
  eyebrow: "Gallery",
  title: "Craftsmanship in Every Detail",
  description:
    "Explore our portfolio of aluminium installations, glass systems, facades, and interior executions across Gujarat.",
} as const;

export const GALLERY_CATEGORIES: GalleryCategoryOption[] = [
  { value: "all", label: "All" },
  { value: "residential", label: "Residential" },
  { value: "commercial", label: "Commercial" },
  { value: "windows-doors", label: "Windows & Doors" },
  { value: "glass", label: "Glass" },
  { value: "facades", label: "Facades" },
  { value: "interiors", label: "Interiors" },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gw-01",
    title: "Panoramic Living Room Windows",
    category: "windows-doors",
    alt: "Floor-to-ceiling aluminium windows in luxury living room",
    src: "/images/gallery/gw-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "gw-02",
    title: "Sliding Terrace Doors",
    category: "windows-doors",
    alt: "Multi-track sliding doors opening to terrace",
    src: "/images/gallery/gw-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "res-01",
    title: "Skyline Residence Facade",
    category: "residential",
    alt: "Residential tower with premium aluminium glazing",
    src: "/images/gallery/res-01.svg",
    width: 800,
    height: 600,
  },
  {
    id: "res-02",
    title: "Villa Serene Pool Deck",
    category: "residential",
    alt: "Villa sliding systems overlooking pool area",
    src: "/images/gallery/res-02.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "com-01",
    title: "Meridian Tower Curtain Wall",
    category: "commercial",
    alt: "Commercial curtain wall glazing installation",
    src: "/images/gallery/com-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "com-02",
    title: "TechPark Atrium Skylight",
    category: "commercial",
    alt: "Double-height atrium structural glass skylight",
    src: "/images/gallery/com-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "glass-01",
    title: "Frameless Office Partitions",
    category: "glass",
    alt: "Frameless glass partitions in corporate office",
    src: "/images/gallery/glass-01.svg",
    width: 800,
    height: 600,
  },
  {
    id: "glass-02",
    title: "Glass Meeting Room",
    category: "glass",
    alt: "Acoustic glass meeting room with aluminium frame",
    src: "/images/gallery/glass-02.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "fac-01",
    title: "Horizon Mall Entrance",
    category: "facades",
    alt: "Structural glazing entrance canopy at retail mall",
    src: "/images/gallery/fac-01.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "fac-02",
    title: "ACP Cladding Elevation",
    category: "facades",
    alt: "ACP cladding facade with glass accents",
    src: "/images/gallery/fac-02.svg",
    width: 800,
    height: 600,
  },
  {
    id: "fac-03",
    title: "Structural Glazing Detail",
    category: "facades",
    alt: "Close-up of structural silicone glazed panel",
    src: "/images/gallery/fac-03.svg",
    width: 800,
    height: 600,
  },
  {
    id: "int-01",
    title: "Azure Office Fit-Out",
    category: "interiors",
    alt: "Complete office interior with partitions and ceiling",
    src: "/images/gallery/int-01.svg",
    width: 800,
    height: 600,
  },
  {
    id: "int-02",
    title: "False Ceiling Integration",
    category: "interiors",
    alt: "Gypsum false ceiling with recessed lighting",
    src: "/images/gallery/int-02.svg",
    width: 800,
    height: 1000,
  },
  {
    id: "int-03",
    title: "Showroom Interior",
    category: "interiors",
    alt: "Retail showroom aluminium and glass interior",
    src: "/images/gallery/int-03.svg",
    width: 800,
    height: 600,
  },
  {
    id: "gw-03",
    title: "Casement Window Detail",
    category: "windows-doors",
    alt: "Premium casement window hardware and seal detail",
    src: "/images/gallery/gw-03.svg",
    width: 800,
    height: 600,
  },
  {
    id: "res-03",
    title: "Riverside Penthouse Terrace",
    category: "residential",
    alt: "Penthouse terrace glass balustrade and windows",
    src: "/images/gallery/res-03.svg",
    width: 800,
    height: 1000,
  },
];
