/* eslint-disable */
// Auto-generated by scripts/generate-work-projects.mjs — do not edit manually.
// Re-run: node scripts/generate-work-projects.mjs

import type { Project, ProjectSlug } from "@/types/projects";

export const PROJECT_SLUGS = [
  "axis-bank",
  "gsfc-uni-acp-work",
  "indian-oil-pump",
  "factory",
  "maruti-public-charitable-trust",
  "residency",
  "house",
  "vip-bags",
  "yusuf-pathan-home"
] as const satisfies readonly ProjectSlug[];

export const PROJECTS: Project[] = [
  {
    "slug": "axis-bank",
    "name": "Axis Bank",
    "category": "Commercial",
    "location": "Vadodara, Gujarat",
    "shortDescription": "Complete aluminium glazing, facade, and interior aluminium work for a premium bank branch.",
    "metaDescription": "Axis Bank commercial glazing project in Vadodara by Shree Chamunda Aluminium. Aluminium windows, facade systems, and professional installation.",
    "keywords": [
      "axis bank vadodara",
      "commercial bank glazing",
      "aluminium facade gujarat"
    ],
    "coverImage": "/work/Projects/axis%20bank/IMG-20240930-WA0036.jpg",
    "description": [
      "A full-scope commercial fit-out for Axis Bank featuring precision-engineered aluminium window systems, glazed partitions, and facade elements tailored to brand standards.",
      "Our team managed measurement, fabrication, and installation with minimal disruption to banking operations, delivering a polished, durable finish built for high footfall."
    ],
    "gallery": [
      {
        "src": "/work/Projects/axis%20bank/IMG-20240930-WA0036.jpg",
        "alt": "Axis Bank — site photo 1"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20240930-WA0037.jpg",
        "alt": "Axis Bank — site photo 2"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20240930-WA0038.jpg",
        "alt": "Axis Bank — site photo 3"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20240930-WA0039.jpg",
        "alt": "Axis Bank — site photo 4"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20240930-WA0042.jpg",
        "alt": "Axis Bank — site photo 5"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20240930-WA0044.jpg",
        "alt": "Axis Bank — site photo 6"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0015.jpg",
        "alt": "Axis Bank — site photo 7"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0016.jpg",
        "alt": "Axis Bank — site photo 8"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0019.jpg",
        "alt": "Axis Bank — site photo 9"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0021.jpg",
        "alt": "Axis Bank — site photo 10"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0022.jpg",
        "alt": "Axis Bank — site photo 11"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0024.jpg",
        "alt": "Axis Bank — site photo 12"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0026.jpg",
        "alt": "Axis Bank — site photo 13"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0030.jpg",
        "alt": "Axis Bank — site photo 14"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0031.jpg",
        "alt": "Axis Bank — site photo 15"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0032.jpg",
        "alt": "Axis Bank — site photo 16"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0033.jpg",
        "alt": "Axis Bank — site photo 17"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0035.jpg",
        "alt": "Axis Bank — site photo 18"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0038.jpg",
        "alt": "Axis Bank — site photo 19"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG-20250120-WA0039.jpg",
        "alt": "Axis Bank — site photo 20"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG20250120170433.jpg",
        "alt": "Axis Bank — site photo 21"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG20250120170441.jpg",
        "alt": "Axis Bank — site photo 22"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG20250120174732.jpg",
        "alt": "Axis Bank — site photo 23"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG20250120174744.jpg",
        "alt": "Axis Bank — site photo 24"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG20250120181248%20-%20Copy.jpg",
        "alt": "Axis Bank — site photo 25"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG20250120181248.jpg",
        "alt": "Axis Bank — site photo 26"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG_20240303_170800.jpg",
        "alt": "Axis Bank — site photo 27"
      },
      {
        "src": "/work/Projects/axis%20bank/IMG_20240303_171451.jpg",
        "alt": "Axis Bank — site photo 28"
      }
    ],
    "servicesUsed": [
      {
        "slug": "structural-glazing",
        "title": "Structural Glazing"
      },
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "glass-partitions",
        "title": "Glass Partitions"
      }
    ],
    "completion": {
      "completedDate": "January 2025",
      "duration": "8 weeks",
      "scope": "Aluminium glazing and interior systems",
      "area": "Commercial branch",
      "client": "Axis Bank"
    },
    "featured": true
  },
  {
    "slug": "gsfc-uni-acp-work",
    "name": "GSFC Uni ACP Work",
    "category": "ACP Cladding",
    "location": "Vadodara, Gujarat",
    "shortDescription": "Premium ACP cladding and facade panel installation for GSFC Uni building.",
    "metaDescription": "GSFC Uni ACP cladding project in Vadodara. Aluminium composite panel facade installation by Shree Chamunda Aluminium.",
    "keywords": [
      "GSFC ACP cladding",
      "ACP facade vadodara",
      "aluminium composite panels gujarat"
    ],
    "coverImage": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241210173113.jpg",
    "description": [
      "A landmark ACP cladding assignment for GSFC Uni, transforming the building envelope with clean lines, uniform panel alignment, and a premium exterior finish.",
      "Our installation team executed precise sub-framing, panel fixing, and quality checks to ensure long-term weather resistance and visual consistency across all elevations."
    ],
    "gallery": [
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241210173113.jpg",
        "alt": "GSFC Uni ACP Work — site photo 1"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241210173135.jpg",
        "alt": "GSFC Uni ACP Work — site photo 2"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241210173219.jpg",
        "alt": "GSFC Uni ACP Work — site photo 3"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241210173242.jpg",
        "alt": "GSFC Uni ACP Work — site photo 4"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241210173251.jpg",
        "alt": "GSFC Uni ACP Work — site photo 5"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241213171305.jpg",
        "alt": "GSFC Uni ACP Work — site photo 6"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241215183527.jpg",
        "alt": "GSFC Uni ACP Work — site photo 7"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241215183547.jpg",
        "alt": "GSFC Uni ACP Work — site photo 8"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241215183635.jpg",
        "alt": "GSFC Uni ACP Work — site photo 9"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241215183650.jpg",
        "alt": "GSFC Uni ACP Work — site photo 10"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241215183732.jpg",
        "alt": "GSFC Uni ACP Work — site photo 11"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241216200328.jpg",
        "alt": "GSFC Uni ACP Work — site photo 12"
      },
      {
        "src": "/work/Projects/GSFC%20UNI%20ACP%20WORK/IMG20241216200401.jpg",
        "alt": "GSFC Uni ACP Work — site photo 13"
      }
    ],
    "servicesUsed": [
      {
        "slug": "acp-cladding",
        "title": "ACP Cladding"
      },
      {
        "slug": "structural-glazing",
        "title": "Structural Glazing"
      }
    ],
    "completion": {
      "completedDate": "December 2024",
      "duration": "5 weeks",
      "scope": "ACP facade cladding",
      "area": "Institutional building",
      "client": "GSFC Uni"
    },
    "featured": true
  },
  {
    "slug": "indian-oil-pump",
    "name": "Indian Oil Pump",
    "category": "Commercial",
    "location": "Gujarat",
    "shortDescription": "Aluminium and glazing work for an Indian Oil retail outlet with durable, low-maintenance finishes.",
    "metaDescription": "Indian Oil pump station aluminium work in Gujarat by Shree Chamunda Aluminium. Commercial glazing and facade solutions.",
    "keywords": [
      "indian oil pump glazing",
      "petrol pump aluminium work",
      "commercial outlet gujarat"
    ],
    "coverImage": "/work/Projects/indian%20oil%20pump/IMG-20260314-WA0006.jpg",
    "description": [
      "This Indian Oil outlet project required practical, hard-wearing aluminium systems for the canopy, office, and customer areas with finishes that withstand outdoor exposure.",
      "We delivered weather-resistant profiles and panels aligned with the operational needs of a high-traffic fuel retail environment."
    ],
    "gallery": [
      {
        "src": "/work/Projects/indian%20oil%20pump/IMG-20260314-WA0006.jpg",
        "alt": "Indian Oil Pump — site photo 1"
      },
      {
        "src": "/work/Projects/indian%20oil%20pump/IMG-20260314-WA0007.jpg",
        "alt": "Indian Oil Pump — site photo 2"
      },
      {
        "src": "/work/Projects/indian%20oil%20pump/IMG-20260314-WA0008.jpg",
        "alt": "Indian Oil Pump — site photo 3"
      }
    ],
    "servicesUsed": [
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "acp-cladding",
        "title": "ACP Cladding"
      }
    ],
    "completion": {
      "completedDate": "March 2026",
      "duration": "3 weeks",
      "scope": "Outlet aluminium and cladding",
      "area": "Fuel retail station",
      "client": "Indian Oil"
    }
  },
  {
    "slug": "factory",
    "name": "Industrial Factory",
    "category": "Industrial",
    "location": "Gujarat",
    "shortDescription": "Large-scale aluminium window, door, and cladding solutions for an industrial manufacturing facility.",
    "metaDescription": "Industrial factory aluminium and glazing project by Shree Chamunda Aluminium. Windows, doors, and facade systems for manufacturing facilities in Gujarat.",
    "keywords": [
      "factory aluminium windows",
      "industrial glazing gujarat",
      "manufacturing facility facade"
    ],
    "coverImage": "/work/Projects/factory/IMG20250430180528.jpg",
    "description": [
      "This industrial project required robust aluminium systems capable of withstanding daily operational demands while maximising natural light across production and office zones.",
      "We supplied and installed high-durability window and door packages with weather-sealed profiles suited to Gujarat's climate conditions."
    ],
    "gallery": [
      {
        "src": "/work/Projects/factory/IMG20250430180528.jpg",
        "alt": "Industrial Factory — site photo 1"
      },
      {
        "src": "/work/Projects/factory/IMG20250430180859.jpg",
        "alt": "Industrial Factory — site photo 2"
      },
      {
        "src": "/work/Projects/factory/IMG20250807182333.jpg",
        "alt": "Industrial Factory — site photo 3"
      },
      {
        "src": "/work/Projects/factory/IMG20250807182355.jpg",
        "alt": "Industrial Factory — site photo 4"
      },
      {
        "src": "/work/Projects/factory/IMG20250807182423.jpg",
        "alt": "Industrial Factory — site photo 5"
      },
      {
        "src": "/work/Projects/factory/IMG20250807182510.jpg",
        "alt": "Industrial Factory — site photo 6"
      },
      {
        "src": "/work/Projects/factory/IMG20250807182549.jpg",
        "alt": "Industrial Factory — site photo 7"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183457.jpg",
        "alt": "Industrial Factory — site photo 8"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183542.jpg",
        "alt": "Industrial Factory — site photo 9"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183601.jpg",
        "alt": "Industrial Factory — site photo 10"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183707.jpg",
        "alt": "Industrial Factory — site photo 11"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183726.jpg",
        "alt": "Industrial Factory — site photo 12"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183817.jpg",
        "alt": "Industrial Factory — site photo 13"
      },
      {
        "src": "/work/Projects/factory/IMG20250807183833.jpg",
        "alt": "Industrial Factory — site photo 14"
      },
      {
        "src": "/work/Projects/factory/IMG20250807184316.jpg",
        "alt": "Industrial Factory — site photo 15"
      }
    ],
    "servicesUsed": [
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "sliding-doors",
        "title": "Sliding Doors"
      },
      {
        "slug": "acp-cladding",
        "title": "ACP Cladding"
      }
    ],
    "completion": {
      "completedDate": "August 2025",
      "duration": "6 weeks",
      "scope": "Windows, doors, and cladding",
      "area": "Industrial facility",
      "client": "Private Manufacturing Unit"
    },
    "featured": true
  },
  {
    "slug": "maruti-public-charitable-trust",
    "name": "Maruti Public Charitable Trust",
    "category": "Institutional",
    "location": "Gujarat",
    "shortDescription": "Aluminium window and facade work for a charitable trust building with functional, long-lasting systems.",
    "metaDescription": "Maruti Public Charitable Trust building aluminium work by Shree Chamunda Aluminium. Institutional glazing in Gujarat.",
    "keywords": [
      "charitable trust building",
      "institutional glazing gujarat",
      "aluminium windows trust"
    ],
    "coverImage": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240407_124035.jpg",
    "description": [
      "We completed aluminium window and glazing installations for the Maruti Public Charitable Trust facility, balancing durability with a welcoming, well-lit interior environment.",
      "The project was executed with careful scheduling to minimise disruption to the trust's daily activities."
    ],
    "gallery": [
      {
        "src": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240407_124035.jpg",
        "alt": "Maruti Public Charitable Trust — site photo 1"
      },
      {
        "src": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240407_124126.jpg",
        "alt": "Maruti Public Charitable Trust — site photo 2"
      },
      {
        "src": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240407_124202.jpg",
        "alt": "Maruti Public Charitable Trust — site photo 3"
      },
      {
        "src": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240505_151756.jpg",
        "alt": "Maruti Public Charitable Trust — site photo 4"
      },
      {
        "src": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240505_151807.jpg",
        "alt": "Maruti Public Charitable Trust — site photo 5"
      },
      {
        "src": "/work/Projects/Maruti%20Public%20Charitable%20Trus/IMG_20240505_151811.jpg",
        "alt": "Maruti Public Charitable Trust — site photo 6"
      }
    ],
    "servicesUsed": [
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "glass-partitions",
        "title": "Glass Partitions"
      }
    ],
    "completion": {
      "completedDate": "May 2024",
      "duration": "4 weeks",
      "scope": "Windows and interior glazing",
      "area": "Institutional building",
      "client": "Maruti Public Charitable Trust"
    }
  },
  {
    "slug": "residency",
    "name": "Residency",
    "category": "Residential",
    "location": "Gujarat",
    "shortDescription": "Premium aluminium window and door systems for a multi-unit residency development.",
    "metaDescription": "Residency aluminium window project in Gujarat by Shree Chamunda Aluminium. Residential glazing for apartment and residency buildings.",
    "keywords": [
      "residency windows gujarat",
      "apartment aluminium glazing",
      "residential facade"
    ],
    "coverImage": "/work/Projects/residency/281020101175.jpg",
    "description": [
      "This residency project called for consistent aluminium window packages across multiple units, ensuring uniform quality, smooth operation, and an elevated exterior appearance.",
      "Our team coordinated batch fabrication and phased installation to meet the project timeline efficiently."
    ],
    "gallery": [
      {
        "src": "/work/Projects/residency/281020101175.jpg",
        "alt": "Residency — site photo 1"
      },
      {
        "src": "/work/Projects/residency/281020101177.jpg",
        "alt": "Residency — site photo 2"
      },
      {
        "src": "/work/Projects/residency/IMG_20130827_150134637.jpg",
        "alt": "Residency — site photo 3"
      },
      {
        "src": "/work/Projects/residency/IMG_20130827_150152200.jpg",
        "alt": "Residency — site photo 4"
      },
      {
        "src": "/work/Projects/residency/IMG_20130916_130924734-1.jpg",
        "alt": "Residency — site photo 5"
      }
    ],
    "servicesUsed": [
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "sliding-doors",
        "title": "Sliding Doors"
      }
    ],
    "completion": {
      "completedDate": "2013–2014",
      "duration": "5 weeks",
      "scope": "Residency window package",
      "area": "Multi-unit residence",
      "client": "Private Developer"
    }
  },
  {
    "slug": "house",
    "name": "Residential Homes",
    "category": "Residential",
    "location": "Gujarat",
    "shortDescription": "A portfolio of residential aluminium window, door, and glazing installations across multiple homes.",
    "metaDescription": "Residential aluminium window and door projects across Gujarat by Shree Chamunda Aluminium. Premium home glazing solutions.",
    "keywords": [
      "residential aluminium windows",
      "home glazing gujarat",
      "house windows vadodara"
    ],
    "coverImage": "/work/Projects/house/IMG-20171224-WA0023jpg.0.jpg",
    "description": [
      "Our residential portfolio spans multiple homes across Gujarat, each with custom-measured aluminium window and door systems designed for comfort, security, and modern aesthetics.",
      "From sliding systems opening to gardens and terraces to fixed glazing for stairwells and bedrooms, every installation reflects our commitment to craftsmanship and clean finishing."
    ],
    "gallery": [
      {
        "src": "/work/Projects/house/IMG-20171224-WA0023jpg.0.jpg",
        "alt": "Residential Homes — site photo 1"
      },
      {
        "src": "/work/Projects/house/IMG-20180201-WA0047jpg.0.jpg",
        "alt": "Residential Homes — site photo 2"
      },
      {
        "src": "/work/Projects/house/IMG-20180619-WA0012jpg.0.jpg",
        "alt": "Residential Homes — site photo 3"
      },
      {
        "src": "/work/Projects/house/IMG-20181101-WA0047-1.jpg",
        "alt": "Residential Homes — site photo 4"
      },
      {
        "src": "/work/Projects/house/IMG-20181101-WA0048-1.jpg",
        "alt": "Residential Homes — site photo 5"
      },
      {
        "src": "/work/Projects/house/IMG-20181116-WA0000-1.jpg",
        "alt": "Residential Homes — site photo 6"
      },
      {
        "src": "/work/Projects/house/IMG-20200103-WA0031.jpg",
        "alt": "Residential Homes — site photo 7"
      },
      {
        "src": "/work/Projects/house/IMG-20210304-WA0055.jpg",
        "alt": "Residential Homes — site photo 8"
      },
      {
        "src": "/work/Projects/house/IMG-20210708-WA0042.jpg",
        "alt": "Residential Homes — site photo 9"
      },
      {
        "src": "/work/Projects/house/IMG-20210708-WA0042_1.jpg",
        "alt": "Residential Homes — site photo 10"
      },
      {
        "src": "/work/Projects/house/IMG-20210708-WA0043.jpg",
        "alt": "Residential Homes — site photo 11"
      },
      {
        "src": "/work/Projects/house/IMG-20210708-WA0044.jpg",
        "alt": "Residential Homes — site photo 12"
      },
      {
        "src": "/work/Projects/house/IMG-20210708-WA0045.jpg",
        "alt": "Residential Homes — site photo 13"
      },
      {
        "src": "/work/Projects/house/IMG-20221203-WA0038.jpg",
        "alt": "Residential Homes — site photo 14"
      },
      {
        "src": "/work/Projects/house/IMG-20230804-WA0028.jpg",
        "alt": "Residential Homes — site photo 15"
      },
      {
        "src": "/work/Projects/house/IMG-20230804-WA0031.jpg",
        "alt": "Residential Homes — site photo 16"
      },
      {
        "src": "/work/Projects/house/IMG-20230804-WA0032.jpg",
        "alt": "Residential Homes — site photo 17"
      },
      {
        "src": "/work/Projects/house/IMG-20240307-WA0032.jpg",
        "alt": "Residential Homes — site photo 18"
      },
      {
        "src": "/work/Projects/house/IMG-20240307-WA0035.jpg",
        "alt": "Residential Homes — site photo 19"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0019.jpg",
        "alt": "Residential Homes — site photo 20"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0020.jpg",
        "alt": "Residential Homes — site photo 21"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0021.jpg",
        "alt": "Residential Homes — site photo 22"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0022.jpg",
        "alt": "Residential Homes — site photo 23"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0023.jpg",
        "alt": "Residential Homes — site photo 24"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0024.jpg",
        "alt": "Residential Homes — site photo 25"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0025.jpg",
        "alt": "Residential Homes — site photo 26"
      },
      {
        "src": "/work/Projects/house/IMG-20260608-WA0026.jpg",
        "alt": "Residential Homes — site photo 27"
      },
      {
        "src": "/work/Projects/house/IMG20210219183739.jpg",
        "alt": "Residential Homes — site photo 28"
      },
      {
        "src": "/work/Projects/house/IMG20210219193737.jpg",
        "alt": "Residential Homes — site photo 29"
      },
      {
        "src": "/work/Projects/house/IMG20210305120322.jpg",
        "alt": "Residential Homes — site photo 30"
      },
      {
        "src": "/work/Projects/house/IMG20210419123237.jpg",
        "alt": "Residential Homes — site photo 31"
      },
      {
        "src": "/work/Projects/house/IMG20210419123242.jpg",
        "alt": "Residential Homes — site photo 32"
      },
      {
        "src": "/work/Projects/house/IMG20210419123250.jpg",
        "alt": "Residential Homes — site photo 33"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112001.jpg",
        "alt": "Residential Homes — site photo 34"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112015.jpg",
        "alt": "Residential Homes — site photo 35"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112041.jpg",
        "alt": "Residential Homes — site photo 36"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112058.jpg",
        "alt": "Residential Homes — site photo 37"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112125.jpg",
        "alt": "Residential Homes — site photo 38"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112143.jpg",
        "alt": "Residential Homes — site photo 39"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112210.jpg",
        "alt": "Residential Homes — site photo 40"
      },
      {
        "src": "/work/Projects/house/IMG_20221212_112334.jpg",
        "alt": "Residential Homes — site photo 41"
      },
      {
        "src": "/work/Projects/house/IMG_20230222_131647.jpg",
        "alt": "Residential Homes — site photo 42"
      },
      {
        "src": "/work/Projects/house/IMG_20240227_165420.jpg",
        "alt": "Residential Homes — site photo 43"
      },
      {
        "src": "/work/Projects/house/IMG_20240227_165513.jpg",
        "alt": "Residential Homes — site photo 44"
      },
      {
        "src": "/work/Projects/house/IMG_20240227_165744.jpg",
        "alt": "Residential Homes — site photo 45"
      },
      {
        "src": "/work/Projects/house/IMG_20240303_141341.jpg",
        "alt": "Residential Homes — site photo 46"
      },
      {
        "src": "/work/Projects/house/IMG_20240303_141350.jpg",
        "alt": "Residential Homes — site photo 47"
      },
      {
        "src": "/work/Projects/house/IMG_20240303_151022.jpg",
        "alt": "Residential Homes — site photo 48"
      },
      {
        "src": "/work/Projects/house/IMG_20240303_151203.jpg",
        "alt": "Residential Homes — site photo 49"
      },
      {
        "src": "/work/Projects/house/IMG_20240401_175607.jpg",
        "alt": "Residential Homes — site photo 50"
      },
      {
        "src": "/work/Projects/house/IMG_20240401_175616.jpg",
        "alt": "Residential Homes — site photo 51"
      }
    ],
    "servicesUsed": [
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "sliding-doors",
        "title": "Sliding Doors"
      },
      {
        "slug": "interior-work",
        "title": "Interior Work"
      }
    ],
    "completion": {
      "completedDate": "Ongoing portfolio",
      "duration": "Varies by home",
      "scope": "Windows, doors, and glazing",
      "area": "Multiple residences",
      "client": "Private Homeowners"
    }
  },
  {
    "slug": "vip-bags",
    "name": "VIP Bags",
    "category": "Commercial",
    "location": "Gujarat",
    "shortDescription": "Retail storefront aluminium and glazing work for a VIP Bags showroom.",
    "metaDescription": "VIP Bags showroom aluminium and glazing project by Shree Chamunda Aluminium. Commercial retail facade Gujarat.",
    "keywords": [
      "VIP bags showroom",
      "retail glazing gujarat",
      "storefront aluminium"
    ],
    "coverImage": "/work/Projects/vip%20bags/IMG20260309211932.jpg",
    "description": [
      "The VIP Bags retail project focused on creating an inviting storefront with clear display glazing and durable aluminium framing suited to a busy commercial environment.",
      "We delivered a clean, brand-appropriate facade that highlights products while maintaining security and weather protection."
    ],
    "gallery": [
      {
        "src": "/work/Projects/vip%20bags/IMG20260309211932.jpg",
        "alt": "VIP Bags — site photo 1"
      },
      {
        "src": "/work/Projects/vip%20bags/IMG20260309212014.jpg",
        "alt": "VIP Bags — site photo 2"
      },
      {
        "src": "/work/Projects/vip%20bags/IMG_20260309_221209.jpg",
        "alt": "VIP Bags — site photo 3"
      }
    ],
    "servicesUsed": [
      {
        "slug": "structural-glazing",
        "title": "Structural Glazing"
      },
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      }
    ],
    "completion": {
      "completedDate": "March 2026",
      "duration": "2 weeks",
      "scope": "Showroom glazing and facade",
      "area": "Retail showroom",
      "client": "VIP Bags"
    }
  },
  {
    "slug": "yusuf-pathan-home",
    "name": "Yusuf Pathan Home",
    "category": "Residential",
    "location": "Gujarat",
    "shortDescription": "Bespoke aluminium window and door installation for a premium private residence.",
    "metaDescription": "Yusuf Pathan home aluminium windows and doors by Shree Chamunda Aluminium. Luxury residential glazing in Gujarat.",
    "keywords": [
      "luxury home windows gujarat",
      "celebrity home glazing",
      "premium aluminium residence"
    ],
    "coverImage": "/work/Projects/yusuf%20pathan%20home/IMG_20120501_152615%20-%20Copy.jpg",
    "description": [
      "A premium residential assignment featuring custom aluminium window and door systems designed for large openings, natural light, and a refined architectural finish.",
      "Every detail — from hardware selection to final alignment — was executed to meet the elevated standards expected of a high-profile private home."
    ],
    "gallery": [
      {
        "src": "/work/Projects/yusuf%20pathan%20home/IMG_20120501_152615%20-%20Copy.jpg",
        "alt": "Yusuf Pathan Home — site photo 1"
      },
      {
        "src": "/work/Projects/yusuf%20pathan%20home/IMG_20120501_152615.jpg",
        "alt": "Yusuf Pathan Home — site photo 2"
      },
      {
        "src": "/work/Projects/yusuf%20pathan%20home/IMG_20120501_154142.jpg",
        "alt": "Yusuf Pathan Home — site photo 3"
      }
    ],
    "servicesUsed": [
      {
        "slug": "aluminium-windows",
        "title": "Aluminium Windows"
      },
      {
        "slug": "sliding-doors",
        "title": "Sliding Doors"
      },
      {
        "slug": "structural-glazing",
        "title": "Structural Glazing"
      }
    ],
    "completion": {
      "completedDate": "2012",
      "duration": "4 weeks",
      "scope": "Full home window and door package",
      "area": "Private residence",
      "client": "Private Residence"
    }
  }
];
