/* eslint-disable */
// Auto-generated by scripts/generate-work-services.mjs — do not edit manually.
// Re-run: node scripts/generate-work-services.mjs

import type { ServiceGalleryImage, ServiceSlug } from "@/types/services";

export type WorkServiceImages = {
  hero: string;
  heroAlt: string;
  gallery: ServiceGalleryImage[];
};

export const WORK_SERVICE_IMAGES: Record<ServiceSlug, WorkServiceImages> = {
  "aluminium-windows": {
    "hero": "/work/Services/alu%20windows/DSC00176.JPG",
    "heroAlt": "Aluminium Windows installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/alu%20windows/DSC00176.JPG",
        "alt": "Aluminium Windows — installation photo 1"
      },
      {
        "src": "/work/Services/alu%20windows/DSC00186.JPG",
        "alt": "Aluminium Windows — installation photo 2"
      },
      {
        "src": "/work/Services/alu%20windows/IMG-20210304-WA0055.jpg",
        "alt": "Aluminium Windows — installation photo 3"
      },
      {
        "src": "/work/Services/alu%20windows/IMG-20210306-WA0065.jpg",
        "alt": "Aluminium Windows — installation photo 4"
      },
      {
        "src": "/work/Services/alu%20windows/IMG-20240307-WA0032.jpg",
        "alt": "Aluminium Windows — installation photo 5"
      },
      {
        "src": "/work/Services/alu%20windows/IMG_20120405_134922-1.jpg",
        "alt": "Aluminium Windows — installation photo 6"
      }
    ]
  },
  "sliding-doors": {
    "hero": "/work/Services/sliding%20doors/IMG-20230409-WA0007.jpg",
    "heroAlt": "Sliding Doors installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/sliding%20doors/IMG-20230409-WA0007.jpg",
        "alt": "Sliding Doors — installation photo 1"
      },
      {
        "src": "/work/Services/sliding%20doors/IMG20260606184111.jpg",
        "alt": "Sliding Doors — installation photo 2"
      },
      {
        "src": "/work/Services/sliding%20doors/IMG20260606184121.jpg",
        "alt": "Sliding Doors — installation photo 3"
      },
      {
        "src": "/work/Services/sliding%20doors/IMG20260606184144.jpg",
        "alt": "Sliding Doors — installation photo 4"
      },
      {
        "src": "/work/Services/sliding%20doors/IMG20260608154713.jpg",
        "alt": "Sliding Doors — installation photo 5"
      },
      {
        "src": "/work/Services/sliding%20doors/IMG_20130905_123810834_1.jpg",
        "alt": "Sliding Doors — installation photo 6"
      },
      {
        "src": "/work/Services/sliding%20doors/IMG_20130905_124033885_1.jpg",
        "alt": "Sliding Doors — installation photo 7"
      }
    ]
  },
  "glass-partitions": {
    "hero": "/work/Services/glass%20partiton/IMG-20211101-WA0065.jpg",
    "heroAlt": "Glass Partitions installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/glass%20partiton/IMG-20211101-WA0065.jpg",
        "alt": "Glass Partitions — installation photo 1"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG-20230428-WA0061.jpg",
        "alt": "Glass Partitions — installation photo 2"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG-20240321-WA0040.jpg",
        "alt": "Glass Partitions — installation photo 3"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG-20241010-WA0023.jpg",
        "alt": "Glass Partitions — installation photo 4"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG-20260608-WA0024.jpg",
        "alt": "Glass Partitions — installation photo 5"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG-20260608-WA0025.jpg",
        "alt": "Glass Partitions — installation photo 6"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG-20260608-WA0026.jpg",
        "alt": "Glass Partitions — installation photo 7"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG_20130905_123724117_1.jpg",
        "alt": "Glass Partitions — installation photo 8"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG_20130905_124033885_1.jpg",
        "alt": "Glass Partitions — installation photo 9"
      },
      {
        "src": "/work/Services/glass%20partiton/IMG_20210829_195654_1.jpg",
        "alt": "Glass Partitions — installation photo 10"
      }
    ]
  },
  "acp-cladding": {
    "hero": "/work/Services/acp%20clladding/IMG20241213171305.jpg",
    "heroAlt": "ACP Cladding installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/acp%20clladding/IMG20241213171305.jpg",
        "alt": "ACP Cladding — installation photo 1"
      },
      {
        "src": "/work/Services/acp%20clladding/IMG20241215183527.jpg",
        "alt": "ACP Cladding — installation photo 2"
      },
      {
        "src": "/work/Services/acp%20clladding/IMG20241215183547.jpg",
        "alt": "ACP Cladding — installation photo 3"
      },
      {
        "src": "/work/Services/acp%20clladding/IMG20241215183732.jpg",
        "alt": "ACP Cladding — installation photo 4"
      },
      {
        "src": "/work/Services/acp%20clladding/IMG20241216200328.jpg",
        "alt": "ACP Cladding — installation photo 5"
      }
    ]
  },
  "structural-glazing": {
    "hero": "/work/Services/Structural%20Glazing/IMG_20130913_142704590-1.jpg",
    "heroAlt": "Structural Glazing installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/Structural%20Glazing/IMG_20130913_142704590-1.jpg",
        "alt": "Structural Glazing — installation photo 1"
      },
      {
        "src": "/work/Services/Structural%20Glazing/IMG_20130916_131015873-1.jpg",
        "alt": "Structural Glazing — installation photo 2"
      },
      {
        "src": "/work/Services/Structural%20Glazing/IMG_20130916_131323662.jpg",
        "alt": "Structural Glazing — installation photo 3"
      },
      {
        "src": "/work/Services/Structural%20Glazing/IMG_20130916_153000285.jpg",
        "alt": "Structural Glazing — installation photo 4"
      },
      {
        "src": "/work/Services/Structural%20Glazing/IMG_20130916_153430830.jpg",
        "alt": "Structural Glazing — installation photo 5"
      },
      {
        "src": "/work/Services/Structural%20Glazing/IMG_20130916_153638907.jpg",
        "alt": "Structural Glazing — installation photo 6"
      },
      {
        "src": "/work/Services/Structural%20Glazing/P270210_12.52.JPG",
        "alt": "Structural Glazing — installation photo 7"
      }
    ]
  },
  "office-partitions": {
    "hero": "/work/Services/office%20partirons/IMG-20190207-WA0014_1.jpg",
    "heroAlt": "Office Partitions installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/office%20partirons/IMG-20190207-WA0014_1.jpg",
        "alt": "Office Partitions — installation photo 1"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20190207-WA0016_1.jpg",
        "alt": "Office Partitions — installation photo 2"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20190207-WA0016_2.jpg",
        "alt": "Office Partitions — installation photo 3"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20190606-WA0009.jpg",
        "alt": "Office Partitions — installation photo 4"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20190625-WA0033.jpg",
        "alt": "Office Partitions — installation photo 5"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20190625-WA0033_1.jpg",
        "alt": "Office Partitions — installation photo 6"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20211101-WA0065.jpg",
        "alt": "Office Partitions — installation photo 7"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20220603-WA0057.jpg",
        "alt": "Office Partitions — installation photo 8"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20220930-WA0038.jpg",
        "alt": "Office Partitions — installation photo 9"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20230428-WA0061.jpg",
        "alt": "Office Partitions — installation photo 10"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20230428-WA0062.jpg",
        "alt": "Office Partitions — installation photo 11"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20240203-WA0024.jpg",
        "alt": "Office Partitions — installation photo 12"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20240321-WA0040.jpg",
        "alt": "Office Partitions — installation photo 13"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20240930-WA0042.jpg",
        "alt": "Office Partitions — installation photo 14"
      },
      {
        "src": "/work/Services/office%20partirons/IMG-20250511-WA0016.jpg",
        "alt": "Office Partitions — installation photo 15"
      },
      {
        "src": "/work/Services/office%20partirons/IMG20200919131640.jpg",
        "alt": "Office Partitions — installation photo 16"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20130905_123639631_1.jpg",
        "alt": "Office Partitions — installation photo 17"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20130905_123724117_1.jpg",
        "alt": "Office Partitions — installation photo 18"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20130905_124033885_1.jpg",
        "alt": "Office Partitions — installation photo 19"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20130905_124241254.jpg",
        "alt": "Office Partitions — installation photo 20"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20140801_121555_1.jpg",
        "alt": "Office Partitions — installation photo 21"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20160813_170935_1.jpg",
        "alt": "Office Partitions — installation photo 22"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20180907_130041.jpg",
        "alt": "Office Partitions — installation photo 23"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20180907_130215.jpg",
        "alt": "Office Partitions — installation photo 24"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20220521_184951.jpg",
        "alt": "Office Partitions — installation photo 25"
      },
      {
        "src": "/work/Services/office%20partirons/IMG_20230424_135203.jpg",
        "alt": "Office Partitions — installation photo 26"
      }
    ]
  },
  "interior-work": {
    "hero": "/work/Services/Interior/100_0503.jpg",
    "heroAlt": "Interior Work installation by Shree Chamunda Aluminium",
    "gallery": [
      {
        "src": "/work/Services/Interior/100_0503.jpg",
        "alt": "Interior Work — installation photo 1"
      },
      {
        "src": "/work/Services/Interior/100_0507.jpg",
        "alt": "Interior Work — installation photo 2"
      },
      {
        "src": "/work/Services/Interior/100_0508.jpg",
        "alt": "Interior Work — installation photo 3"
      },
      {
        "src": "/work/Services/Interior/100_0509.jpg",
        "alt": "Interior Work — installation photo 4"
      },
      {
        "src": "/work/Services/Interior/100_0511.jpg",
        "alt": "Interior Work — installation photo 5"
      },
      {
        "src": "/work/Services/Interior/IMG-20180215-WA0046jpg.0.jpg",
        "alt": "Interior Work — installation photo 6"
      },
      {
        "src": "/work/Services/Interior/IMG-20200103-WA0030_1.jpg",
        "alt": "Interior Work — installation photo 7"
      },
      {
        "src": "/work/Services/Interior/IMG-20230804-WA0031.jpg",
        "alt": "Interior Work — installation photo 8"
      },
      {
        "src": "/work/Services/Interior/IMG-20230804-WA0032.jpg",
        "alt": "Interior Work — installation photo 9"
      },
      {
        "src": "/work/Services/Interior/IMG-20260608-WA0019.jpg",
        "alt": "Interior Work — installation photo 10"
      },
      {
        "src": "/work/Services/Interior/IMG-20260608-WA0021.jpg",
        "alt": "Interior Work — installation photo 11"
      },
      {
        "src": "/work/Services/Interior/IMG-20260608-WA0022.jpg",
        "alt": "Interior Work — installation photo 12"
      },
      {
        "src": "/work/Services/Interior/IMG20210106100223.jpg",
        "alt": "Interior Work — installation photo 13"
      },
      {
        "src": "/work/Services/Interior/IMG20210419123237.jpg",
        "alt": "Interior Work — installation photo 14"
      },
      {
        "src": "/work/Services/Interior/IMG20210419123242.jpg",
        "alt": "Interior Work — installation photo 15"
      },
      {
        "src": "/work/Services/Interior/IMG20210419123250.jpg",
        "alt": "Interior Work — installation photo 16"
      }
    ]
  }
};
